server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
    throw-exception-if-no-handler-found: true
    converters:
      preferred-json-mapper: jackson

  # 若设置完后mybatis-plus返回时间依然带T，则需要自定义jackson关datetime的序列化与反序列化器
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      sort-properties-alphabetically: true

  output:
    ansi:
      enabled: always

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: ####
      port: ####
      connect-timeout: 1000
      password: ####

  servlet:
    multipart:
      enabled: true
      # 文件附件大小30MB
      max-file-size: 30MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 生产环境 mysql -h host -u root -p 连接内网数据库
    url: ####
    username: root
    password: 123456


mybatis-plus:
  configuration:
    # 是否使用三级缓存
    cache-enabled: true
    # 设置当查询结果值为null时，同样映射该查询字段给map
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      # 逻辑已删除
      logic-delete-value: 1
      # 逻辑未删除
      logic-not-delete-value: 0

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm
  level:
    web: info
  file:
    name: logs

springdoc:
  swagger-ui:
    path: /doc