spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mobile_phone_sales_system?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 010209

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
    throw-exception-if-no-handler-found: true

  # Console Colorful Output
  output:
    ansi:
      enabled: always

  web:
    resources:
      add-mappings: false

  redis:
    host: 127.0.0.1
    port: 6379
    connect-timeout: 1000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: spring-boot

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

logging:
  level:
    web: debug