spring:
  profiles:
    default: dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: ####
    password: ####
    test-connection: true
    default-encoding: UTF-8