server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  data:
    redis:
      host: ####
      port: ####
      connect-timeout: 1000
      password: ####

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /spring-tutorial
    listener:
      simple:
        prefetch: 1 # 每次只能处理一条消息，处理完后再接收下一条消息
    connection-timeout: 1s
    template:
      retry:
        enabled: true # 超时重试
        initial-interval: 1000ms # 失败后初始等待事件
        multiplier: 1 # 失败后下次等待时长倍数
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: none # 发布确认模式
    publisher-returns: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 生产环境 mysql -h host -u root -p 连接内网数据库
    url: ####
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # 是否使用三级缓存
    cache-enabled: true
    # 设置当查询结果值为null时，同样映射该查询字段给map
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      # 逻辑已删除
      logic-delete-value: 1
      # 逻辑未删除
      logic-not-delete-value: 0

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    web: info
  file:
    path: logs
    name: log

springdoc:
  swagger-ui:
    path: /doc