server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
    throw-exception-if-no-handler-found: true
    converters:
      preferred-json-mapper: jackson

  # 若设置完后mybatis-plus返回时间依然带T，则需要自定义jackson关datetime的序列化与反序列化器
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      sort-properties-alphabetically: true

  output:
    ansi:
      enabled: always

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 1000
      password: 123456

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /spring-tutorial
    listener:
      simple:
        prefetch: 1 # 每次只能处理一条消息，处理完后再接收下一条消息
    connection-timeout: 1s
    template:
      retry:
        enabled: true # 超时重试
        initial-interval: 1000ms # 失败后初始等待事件
        multiplier: 1 # 失败后下次等待时长倍数
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: none # 发布确认模式
    publisher-returns: true

  servlet:
    multipart:
      enabled: true
      # 文件附件大小30MB
      max-file-size: 30MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 开发环境
    url: jdbc:mysql://127.0.0.1:3306/SpringTutorial?useUnicode=true&characterEncoding=utf-8&useSSL=true&rewriteBatchedStatements=true
    username: admin
    password: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否使用三级缓存
    cache-enabled: true
    # 设置当查询结果值为null时，同样映射该查询字段给map
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      # 逻辑已删除
      logic-delete-value: 1
      # 逻辑未删除
      logic-not-delete-value: 0

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    web: debug
  file:
    name: log/log.txt

springdoc:
  swagger-ui:
    path: /doc