spring:
  profiles:
    default: dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
    throw-exception-if-no-handler-found: true
    converters:
      preferred-json-mapper: jackson

  # 若设置完后mybatis-plus返回时间依然带T，则需要自定义jackson关datetime的序列化与反序列化器
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      sort-properties-alphabetically: true

  output:
    ansi:
      enabled: always

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      enabled: true
      # 文件附件大小30MB
      max-file-size: 30MB


  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: ####
    password: ####
    test-connection: true
    default-encoding: UTF-8


cos:
  secretId: '####'
  secretKey: '####'
  bucketName: '####'
  region: '####'

tms:
  secretId: '####'
  secretKey: '####'
  bizType: '####'